### ISSUE TITLE
Solver not deciding although quantification has been removed 

### ISSUE THREAD

**Issue by feliciahalim** [feliciahalim/klee#32] opened 2016-03-09 02:32 UTC
There seems to be cases that subsubmption check reports inability of solver to decide (in-)validity although there is no quantified variable in the formula.

**Comment by domainexpert** [comment] 2016-03-09 03:35
This can be observed when running `addition_safe8.c` as input from feliciahalim/klee-examples.

**Comment by domainexpert** [comment] 2016-03-09 09:06
@feliciahalim This is not a bug, as the solver, especially `CexCachingSolver` treats invalidity as unknown result. Commit https://github.com/feliciahalim/klee/commit/f33f6b95bdafb82f7c114e4fb27084b708dc6bda includes comments in `CexCachingSolver::computeValidity` and `SubsumptionTableEntry::subsumed` explaining this. I close this issue now.

**Closed by domainexpert** 2016-03-09 09:06 UTC
